dbinfo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from dbinfo import views

urlpatterns = [
    url(r'^server_list/', views.server_list, name='server_list'),
    url(r'^server_password_list/', views.server_password_list, name='server_password_list'),
    url(r'^oracle_user_list/', views.oracle_user_list, name='oracle_user_list'),
    url(r'mysql_user_list/', views.mysql_user_list, name='mysql_user_list'),
]

issues/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from issues import views

urlpatterns = [
    url(r'^event_list/', views.event_list, name='event_list'),
    url(r'^system_list/', views.system_list, name='system_list'),
    url(r'^person_list/', views.person_list, name='person_list'),
]

itinfo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from itinfo.views import index, login, auth_logout
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^portmap/', include('portmap.urls')),
    url(r'^oportmap/', include('oportmap.urls')),
    url(r'^appinfo/', include('appinfo.urls')),
    url(r'^ipresource/', include('ipresource.urls')),
    url(r'^dbinfo/', include('dbinfo.urls')),
    url(r'^odbinfo/', include('odbinfo.urls')),
    url(r'^issues/', include('issues.urls')),
    url(r'^addressbook/', include('addressbook.urls')),
    url(r'^shortcut/', include('shortcut.urls')),
    url(r'^$', index, name='index'),
    url(r'^index/', index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'login', login, name='login'),
    url(r'auth_logout', auth_logout, name='auth_logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

issues/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models


DEPARTMENT_CHOISE = {(1, '运维部'), (2, '测试部'), (3, '结算部'), (4, '风控部'), (5, '产品部')}
UPDATE_TYPE_CHOISE = {(1, '正常变更'), (2, '紧急变更')}
OP_TYPE_CHOISE = {(1, '系统操作'), (2, '数据库操作'), (3, '混合操作')}


class Person(models.Model):
    name = models.CharField(max_length=50, verbose_name='姓名')
    dept = models.IntegerField(choices=DEPARTMENT_CHOISE, default=1, verbose_name='部门')
    mobile = models.CharField(max_length=50, null=True, blank=True, verbose_name='电话')
    email = models.EmailField(null=True, blank=True, verbose_name='邮箱')
    comment = models.TextField(null=True, blank=True, verbose_name='备注')

    class Meta:
        ordering = ["name"]
        verbose_name = '人员信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.name

    def __str__(self):
        return u'%s' % self.name


class System(models.Model):
    sname = models.CharField(max_length=100, verbose_name='系统名称')
    short_desc = models.CharField(max_length=100, verbose_name='系统简介')
    author = models.ForeignKey(Person, null=True, blank=True, verbose_name='作者')
    comment = models.TextField(null=True, blank=True, verbose_name='详细信息')

    class Meta:
        ordering = ["sname"]
        verbose_name = '系统信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.sname

    def __str__(self):
        return u'%s' % self.sname


class Event(models.Model):
    release = models.IntegerField(verbose_name='事件编号')
    title = models.CharField(max_length=100, verbose_name='标题')
    sponsor = models.ForeignKey(Person, related_name="sp_person",  verbose_name='发起者')
    sp_dept = models.IntegerField(choices=DEPARTMENT_CHOISE, default=5, verbose_name='发起部门')
    update_type = models.IntegerField(choices=UPDATE_TYPE_CHOISE, default=1, verbose_name='变更类型')
    project = models.ForeignKey(System, verbose_name='所属项目')
    operator = models.ForeignKey(Person, related_name="op_person", verbose_name='操作者')
    op_type = models.IntegerField(default=1, choices=OP_TYPE_CHOISE, verbose_name='操作类型')
    begin_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')

    class Meta:
        ordering = ["-begin_time"]
        verbose_name = '上线信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.release

    def __str__(self):
        return u'%s' % self.release

issues/views.py
from django.shortcuts import render, render_to_response
from issues.models import System, Person, Event


def person_list(request):
    person_lists = Person.objects.all()
    return render_to_response('issue/person_list.html', locals())


def system_list(request):
    system_lists = System.objects.all()
    return render_to_response('issue/system_list.html', locals())


def event_list(request):
    event_lists = Event.objects.all()
    return render_to_response('issue/event_list.html', locals())

templates/issue/event_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

    <!-- /#page-wrapper -->
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            变更记录表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover table-condensed" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th width="10%">事件编号</th>
											<th width="20%">标题</th>
											<th width="10%">发起者</th>
                                            <th width="10%">变更类型</th>
                                            <th width="10%">所属项目</th>
                                            <th width="10%">操作者</th>
                                            <th width="10%">操作类型</th>
                                            <th width="20%">操作时间</th>
                                        </tr>
                                    </thead>
                                    <tbody>

{% for event_list in event_lists %}
                                        <tr>
                                            <td>{{event_list.release}}</td>
                                            <td>{{ event_list.title }}</td>
                                            <td><a href="{{ event_list.sponsor }}">{{event_list.get_sp_dept_display }}</a> </td>
                                            <td>{{event_list.get_update_type_display}}</td>
                                            <td>{{event_list.project.sname }}</td>
                                            <td>{{ event_list.operator.name }}</td>
                                            <td>{{event_list.get_op_type_display}}</td>
                                            <td>{{event_list.begin_time}}/{{event_list.begin_time}}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->


{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}

templates/issue/system_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

    <!-- /#page-wrapper -->
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            项目列表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover table-condensed" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th width="20%">项目名称</th>
											<th width="20%">项目简介</th>
											<th width="10%">作者</th>
                                            <th width="50%">详细信息</th>
                                        </tr>
                                    </thead>
                                    <tbody>

{% for system_list in system_lists %}
                                        <tr>
                                            <td>{{system_list.sname}}</td>
                                            <td>{{ system_list.short_desc }}</td>
                                            <td>{{event_list.author }} </td>
                                            <td>{{system_list.comment}}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->


{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}