dbinfo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from dbinfo import views

urlpatterns = [
    url(r'^server_list/', views.server_list, name='server_list'),
    url(r'^server_password_list/', views.server_password_list, name='server_password_list'),
    url(r'^oracle_user_list/', views.oracle_user_list, name='oracle_user_list'),
    url(r'mysql_user_list/', views.mysql_user_list, name='mysql_user_list'),
]

itinfo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from itinfo.views import index, login, auth_logout
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^portmap/', include('portmap.urls')),
    url(r'^oportmap/', include('oportmap.urls')),
    url(r'^appinfo/', include('appinfo.urls')),
    url(r'^ipresource/', include('ipresource.urls')),
    url(r'^dbinfo/', include('dbinfo.urls')),
    url(r'^odbinfo/', include('odbinfo.urls')),
    url(r'^issues/', include('issues.urls')),
    url(r'^addressbook/', include('addressbook.urls')),
    url(r'^shortcut/', include('shortcut.urls')),
    url(r'^$', index, name='index'),
    url(r'^index/', index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'login', login, name='login'),
    url(r'auth_logout', auth_logout, name='auth_logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dbinfo/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models

SERVICE_RANGE_CHOISE = {(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年'), (5, '5年'), (6, '6年'), (7, '7年'), (8, '8年'), (0, '长期')}
USER_STATUS_CHOISE = {(1, '停用'), (2, '正常'), (3, '锁定')}
DBSERVER_POS_CHOISE = {(1, '东单机房'), (2, '中关村机房'), (3, '上海机房')}
FIRM_CHOISE = {(1, 'DELL'), (2, 'IBM'), (3, 'EMC')}


class Dbserver(models.Model):
    name = models.CharField(max_length=30, verbose_name='名称')
    ip = models.GenericIPAddressField(verbose_name='IP')
    pos = models.IntegerField(default=1, choices=DBSERVER_POS_CHOISE, verbose_name='位置')
    sn = models.CharField(null=True, blank=True, max_length=50, verbose_name='序列号')
    sid = models.CharField(null=True, blank=True, max_length=50, verbose_name='快速服务代码')
    firm = models.IntegerField(default=1, choices=FIRM_CHOISE, verbose_name='厂商')
    model = models.CharField(null=True, blank=True, max_length=30, verbose_name='型号')
    feature = models.TextField(null=True, blank=True, verbose_name='配置')
    buy_time = models.DateField(null=True, blank=True, verbose_name='购买时间')
    service_range = models.IntegerField(default=1, choices=SERVICE_RANGE_CHOISE, verbose_name='服务年限')
    comment = models.TextField(null=True, blank=True, verbose_name='备注')

    class Meta:
        ordering = ["name"]
        verbose_name = '生产服务器信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.name

    def __str__(self):
        return u'%s' % self.name


class Users(models.Model):
    dbserver = models.ForeignKey(Dbserver, null=True, blank=True, verbose_name='服务器')
    user = models.CharField(max_length=20, verbose_name='用户名')
    passwd = models.CharField(max_length=20, verbose_name='密码')
    tablespace = models.CharField(max_length=20, null=True, blank=True, verbose_name='表空间')
    status = models.IntegerField(choices=USER_STATUS_CHOISE, verbose_name='状态')
    business = models.CharField(null=True, blank=True, max_length=100, verbose_name='业务')
    created = models.DateField(null=True, blank=True, verbose_name='创建时间')
    comment = models.TextField(null=True, blank=True, verbose_name='备注')

    class Meta:
        ordering = ["user"]
        verbose_name = '生产数据库用户信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.business

    def __str__(self):
        return u'%s' % self.business


class Sysusers(models.Model):
    dbserver = models.ForeignKey(Dbserver, null=True, blank=True, verbose_name='服务器')
    name = models.CharField(max_length=20, verbose_name='名称')
    user = models.CharField(max_length=20, verbose_name='用户')
    passwd = models.CharField(max_length=20, verbose_name='密码')

    class Meta:
        ordering = ["dbserver"]
        verbose_name = '生产系统用户信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.name

    def __str__(self):
        return u'%s' % self.name


class Mysqluser(models.Model):
    dbserver = models.ForeignKey(Dbserver, verbose_name='服务器')
    name = models.CharField(max_length=20, verbose_name='用户名')
    passwd = models.CharField(max_length=20, verbose_name='密码')
    dbname = models.CharField(max_length=20, verbose_name='数据库名')
    business = models.CharField(null=True, blank=True, max_length=100, verbose_name='业务')
    comment = models.TextField(null=True, blank=True, verbose_name='备注')

    class Meta:
        ordering = ["dbserver"]
        verbose_name = '生产MYSQL用户信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.business

    def __str__(self):
        return u'%s' % self.business

dbinfo/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render_to_response

from models import Dbserver, Users, Sysusers, Mysqluser
from datetime import date, datetime


def server_list(request):
    user = request.user.get_username()
    if user != 'yinhb' and user != 'denghui' and user != 'admin':
        return render_to_response('permission_error.html')
    server_lists = Dbserver.objects.all()
    for server in server_lists:
        btime = server.buy_time
        yeard = server.service_range
        if btime is None:
            server.buy_time = 0
            server.service_range = '未知'
        else:
            y = int(btime.year)
            m = str(btime.month)
            d = str(btime.day)
            y = y + yeard
            s_expire = str(y) + '-' + m + '-' + d
            t_expire = datetime.strptime(s_expire, '%Y-%m-%d').date()

            print(t_expire)
            today = date.today()
            distance = (today - t_expire).days
            if distance > 0:
                server.buy_time = 2
            else:
                server.buy_time = 1
            server.service_range = t_expire

    return render_to_response('dbinfo/server_list.html', locals())


def server_password_list(request):
    user = request.user.get_username()
    if user != 'yinhb' and user != 'denghui' and user != 'admin':
        return render_to_response('permission_error.html')

    sysuser_lists = Sysusers.objects.all()
    return render_to_response('dbinfo/server_password.html', locals())


def oracle_user_list(request):
    user = request.user.get_username()
    if user != 'yinhb' and user != 'denghui' and user != 'admin':
        return render_to_response('permission_error.html')

    user_lists = Users.objects.all()
    return render_to_response('dbinfo/ouser_list.html', locals())


def mysql_user_list(request):
    user = request.user.get_username()
    if user != 'yinhb' and user != 'denghui' and user != 'admin':
        return render_to_response('permission_error.html')

    mysql_lists = Mysqluser.objects.all()
    return render_to_response('dbinfo/mysql_list.html',locals())

templates/dbinfo/mysql_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block nav-sjkxx %}
    <li>
        <a href="#"><i class="fa fa-globe"></i> 数据库信息<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse in">
            <li>
                <a href="#">生产环境 <span class="fa arrow"></span></a>
                <ul class="nav nav-third-level">
                    <li> <a href="/dbinfo/server_list">生产服务列表</a></li>
                    <li><a href="/dbinfo/server_password_list">生产服务密码表</a></li>
                    <li> <a href="/dbinfo/oracle_user_list">生产ORACLE用户信息表</a></li>
                    <li><a href="/dbinfo/mysql_user_list">生产MYSQL密码表</a></li>
                </ul>
            </li>
            <li>
                <a href="#">办公环境 <span class="fa arrow"></span></a>
                <ul class="nav nav-third-level">
                    <li> <a href="/odbinfo/o_server_list">办公服务列表</a></li>
                    <li><a href="/odbinfo/o_server_password_list">办公服务器密码表</a></li>
                    <li> <a href="/odbinfo/o_oracle_user_list">办公ORACLE用户信息表</a></li>
                    <li><a href="/odbinfo/o_mysql_user_list">办公MYSQL密码表</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="fa fa-globe"></i> 上线信息<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li> <a href="/issues/event_list">上线列表</a> </li>
            <li> <a href="/issues/system_list">项目列表</a> </li>
        </ul>
    </li>
{% endblock %}
{% block content %}

    <!-- /#page-wrapper -->


    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            生产MYSQL用户信息表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover table-condensed" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th width="10%">服务器</th>
                                            <th width="10%">用户名</th>
											<th width="20%">密码</th>
                                            <th width="10%">数据库</th>
                                            <th width="20%">业务</th>
                                            <th width="20%">备注</th>
                                        </tr>
                                    </thead>
                                    <tbody>

{% for mysql_list in mysql_lists %}
                                        <tr class="odd gradeX">
                                            <td>{{mysql_list.dbserver.ip}}</td>
                                            <td>{{mysql_list.name}}</td>
                                            <td>{{mysql_list.passwd }}</td>
                                            <td>{{mysql_list.dbname}}</td>
                                            <td>{{mysql_list.business}}</td>
                                            <td>{{mysql_list.comment}}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->


{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}

templates/dbinfo/ouser_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block nav-sjkxx %}
    <li>
        <a href="#"><i class="fa fa-globe"></i> 数据库信息<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse in">
            <li>
                <a href="#">生产环境 <span class="fa arrow"></span></a>
                <ul class="nav nav-third-level">
                    <li> <a href="/dbinfo/server_list">生产服务列表</a></li>
                    <li><a href="/dbinfo/server_password_list">生产服务密码表</a></li>
                    <li> <a href="/dbinfo/oracle_user_list">生产ORACLE用户信息表</a></li>
                    <li><a href="/dbinfo/mysql_user_list">生产MYSQL密码表</a></li>
                </ul>
            </li>
            <li>
                <a href="#">办公环境 <span class="fa arrow"></span></a>
                <ul class="nav nav-third-level">
                    <li> <a href="/odbinfo/o_server_list">办公服务列表</a></li>
                    <li><a href="/odbinfo/o_server_password_list">办公服务器密码表</a></li>
                    <li> <a href="/odbinfo/o_oracle_user_list">办公ORACLE用户信息表</a></li>
                    <li><a href="/odbinfo/o_mysql_user_list">办公MYSQL密码表</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="fa fa-globe"></i> 上线信息<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li> <a href="/issues/event_list">上线列表</a> </li>
            <li> <a href="/issues/system_list">项目列表</a> </li>
        </ul>
    </li>
{% endblock %}
{% block content %}

    <!-- /#page-wrapper -->


    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            生产ORACLE用户信息表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover table-condensed" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th width="10%">服务器</th>
                                            <th width="10%">用户名</th>
											<th width="20%">密码</th>
                                            <th width="10%">状态</th>
                                            <th width="20%">业务</th>
                                            <th width="10%">创建时间</th>
                                            <th width="20%">备注</th>
                                        </tr>
                                    </thead>
                                    <tbody>

{% for user_list in user_lists %}
                                        <tr class="odd gradeX">
                                            <td>{{user_list.dbserver.ip}}</td>
                                            <td>{{ user_list.user }}</td>
                                            <td>{{user_list.passwd }}</td>
                                            <td>{{user_list.status}}</td>
                                            <td>{{user_list.business}}</td>
                                            <td>{{user_list.created}}</td>
                                            <td>{{user_list.comment}}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->


{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}

templates/dbinfo/server_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block nav-sjkxx %}
    <li>
        <a href="#"><i class="fa fa-globe"></i> 数据库信息<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse in">
            <li>
                <a href="#">生产环境 <span class="fa arrow"></span></a>
                <ul class="nav nav-third-level">
                    <li> <a href="/dbinfo/server_list">生产服务列表</a></li>
                    <li><a href="/dbinfo/server_password_list">生产服务密码表</a></li>
                    <li> <a href="/dbinfo/oracle_user_list">生产ORACLE用户信息表</a></li>
                    <li><a href="/dbinfo/mysql_user_list">生产MYSQL密码表</a></li>
                </ul>
            </li>
            <li>
                <a href="#">办公环境 <span class="fa arrow"></span></a>
                <ul class="nav nav-third-level">
                    <li> <a href="/odbinfo/o_server_list">办公服务列表</a></li>
                    <li><a href="/odbinfo/o_server_password_list">办公服务器密码表</a></li>
                    <li> <a href="/odbinfo/o_oracle_user_list">办公ORACLE用户信息表</a></li>
                    <li><a href="/odbinfo/o_mysql_user_list">办公MYSQL密码表</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="fa fa-globe"></i> 上线信息<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li> <a href="/issues/event_list">上线列表</a> </li>
            <li> <a href="/issues/system_list">项目列表</a> </li>
        </ul>
    </li>
{% endblock %}
{% block content %}

    <!-- /#page-wrapper -->
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            生产数据库服务器列表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover table-condensed" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th width="10%">ID</th>
											<th width="20%">名称</th>
											<th width="10%">位置</th>
                                            <th width="10%">IP</th>
                                            <th width="10%">型号</th>
                                            <th width="10%">保修</th>
                                            <th width="10%">服务代码</th>
                                            <th width="20%">备注</th>
                                        </tr>
                                    </thead>
                                    <tbody>

{% for server_list in server_lists %}
                                        <tr class="odd gradeX">
                                            <td>{{server_list.id}}</td>
                                            <td>{{ server_list.name }}</td>
                                            <td>{{server_list.get_pos_display }}</td>
                                            <td>{{server_list.ip}}</td>
                                            <td><a herf="#" title="{{server_list.model}}
{{ server_list.feature }}">{{server_list.get_firm_display }}</a></td>
                                            <td>
                                                {% if server_list.buy_time == 1 %}
                                                    <span style="color: #3f903f;" ><a href="#" title="过保时间：{{ server_list.service_range }}">在保</a></span>
                                                {% elif server_list.buy_time == 2 %}
                                                    <span style="color: #FF0000;"> <a href="#" title="过保时间：{{ server_list.service_range }}">过期</a></span>
                                                {% elif server_list.buy_time == 0 %}
                                                    <span style="color:blue"><a href="#" title="过保时间：{{ server_list.service_range }}">未知</a></span>
                                                {% endif %}
                                            </td>
                                            <td><a href="{{ server_list.sid }}" title="{{ server_list.sid }}">{{server_list.sn}}</a></td>
                                            <td>{{server_list.comment}}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->


{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}

templates/dbinfo/server_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block nav-sjkxx %}
    <li>
        <a href="#"><i class="fa fa-globe"></i> 数据库信息<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse in">
            <li>
                <a href="#">生产环境 <span class="fa arrow"></span></a>
                <ul class="nav nav-third-level">
                    <li> <a href="/dbinfo/server_list">生产服务列表</a></li>
                    <li><a href="/dbinfo/server_password_list">生产服务密码表</a></li>
                    <li> <a href="/dbinfo/oracle_user_list">生产ORACLE用户信息表</a></li>
                    <li><a href="/dbinfo/mysql_user_list">生产MYSQL密码表</a></li>
                </ul>
            </li>
            <li>
                <a href="#">办公环境 <span class="fa arrow"></span></a>
                <ul class="nav nav-third-level">
                    <li> <a href="/odbinfo/o_server_list">办公服务列表</a></li>
                    <li><a href="/odbinfo/o_server_password_list">办公服务器密码表</a></li>
                    <li> <a href="/odbinfo/o_oracle_user_list">办公ORACLE用户信息表</a></li>
                    <li><a href="/odbinfo/o_mysql_user_list">办公MYSQL密码表</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="fa fa-globe"></i> 上线信息<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li> <a href="/issues/event_list">上线列表</a> </li>
            <li> <a href="/issues/system_list">项目列表</a> </li>
        </ul>
    </li>
{% endblock %}
{% block content %}

    <!-- /#page-wrapper -->


    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            生产服务器密码表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover table-condensed" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th width="10%">ID</th>
											<th width="20%">服务器</th>
                                            <th width="20%">IP</th>
											<th width="20%">用户</th>
                                            <th width="30%">密码</th>
                                        </tr>
                                    </thead>
                                    <tbody>

{% for sysuser_list in sysuser_lists %}
                                        <tr class="odd gradeX">
                                            <td>{{sysuser_list.id}}</td>
                                            <td>{{ sysuser_list.dbserver.name }}</td>
                                            <td>{{sysuser_list.dbserver.ip }}</td>
                                            <td>{{sysuser_list.user}}</td>
                                            <td>{{sysuser_list.passwd}}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->


{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}