appinfo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from appinfo import views

urlpatterns = [
    url(r'^server_list/', views.server_list, name='server_list'),
    url(r'^app_list/', views.app_list, name='app_list'),
    url(r'^deploy_list/', views.deploy_list, name='deploy_list'),
    url(r'^business_list/', views.business_list, name='business_list'),
]

dbinfo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from dbinfo import views

urlpatterns = [
    url(r'^server_list/', views.server_list, name='server_list'),
    url(r'^server_password_list/', views.server_password_list, name='server_password_list'),
    url(r'^oracle_user_list/', views.oracle_user_list, name='oracle_user_list'),
    url(r'mysql_user_list/', views.mysql_user_list, name='mysql_user_list'),
]

itinfo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from itinfo.views import index, login, auth_logout
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^portmap/', include('portmap.urls')),
    url(r'^oportmap/', include('oportmap.urls')),
    url(r'^appinfo/', include('appinfo.urls')),
    url(r'^ipresource/', include('ipresource.urls')),
    url(r'^dbinfo/', include('dbinfo.urls')),
    url(r'^odbinfo/', include('odbinfo.urls')),
    url(r'^issues/', include('issues.urls')),
    url(r'^addressbook/', include('addressbook.urls')),
    url(r'^shortcut/', include('shortcut.urls')),
    url(r'^$', index, name='index'),
    url(r'^index/', index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'login', login, name='login'),
    url(r'auth_logout', auth_logout, name='auth_logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appinfo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


SERVICE_RANGE_CHOISE = {(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年'), (5, '5年'), (6, '6年'), (7, '7年'), (8, '8年'), (0, '长期')}
DBSERVER_POS_CHOISE = {(1, '生产机房'), (2, '测试机房'), (3, '上海灾备机房'), (4, '中关村机房'), (5, '生产新机房')}
ZONE_CHOISE ={('I', 'INSIDE'), ('O', 'OUTSIDE'), ('D', 'DMZ')}
SERVER_TYPE_CHOISE = {(1, '实体机'), (2, '虚拟机')}
MANU_CHOISE = {(1, 'Dell'), (2, 'IBM'), (3, 'EMC')}


class Server(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name=u'服务器名称')
    ip = models.CharField(max_length=20, blank=True, null=True, verbose_name='服务器IP')
    ext_ip = models.TextField(blank=True, null=True, verbose_name='其他IP')
    zone = models.CharField(max_length=5, blank=True, null=True, choices=ZONE_CHOISE, verbose_name='网络区域')
    sn = models.CharField(max_length=255, blank=True, null=True, verbose_name='编号')
    sid = models.CharField(max_length=255, blank=True, null=True, verbose_name='服务代码')
    manufacturer = models.IntegerField(choices=MANU_CHOISE, blank=True, null=True, verbose_name='品牌')
    mod = models.CharField(max_length=255, blank=True, null=True, verbose_name='型号')
    type = models.IntegerField(choices=SERVER_TYPE_CHOISE, blank=True, null=True, verbose_name='机器类型')
    feature = models.TextField(null=True, blank=True, verbose_name='配置')
    buy_date = models.DateField(blank=True, null=True, verbose_name='购买时间')
    contact = models.CharField(max_length=25, blank=True, null=True, verbose_name='联系人')
    factory_phone = models.CharField(max_length=25, blank=True, null=True, verbose_name='联系电话')
    service_range = models.IntegerField( choices=SERVICE_RANGE_CHOISE, verbose_name='保修')
    cabinet = models.CharField(max_length=20, blank=True, null=True, verbose_name='机柜号')
    idc = models.IntegerField(default=1, choices=DBSERVER_POS_CHOISE, verbose_name='机房')
    comment = models.TextField(blank=True, null=True, verbose_name='备注')

    class Meta:
        ordering = ["ip"]
        verbose_name = '应用服务器信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.ip

    def __str__(self):
        return u'%s' % self.ip


class App(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name='应用名称')
    language = models.CharField(max_length=20, blank=True, null=True, verbose_name='开发语言')
    function = models.CharField(max_length=255, blank=True, null=True, verbose_name='功能')
    teams = models.CharField(max_length=255, blank=True, null=True, verbose_name='开发团队')
    dev_time = models.DateField(blank=True, null=True, verbose_name='开发时间')
    contact = models.CharField(max_length=255, blank=True, null=True, verbose_name='联系人')
    comment = models.TextField(blank=True, null=True, verbose_name='详细说明')

    class Meta:
        ordering = ["name"]
        verbose_name = '应用信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.name

    def __str__(self):
        return u'%s' % self.name


class Deploy(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name='部署名称')
    server = models.ForeignKey(Server, verbose_name='部署服务器')
    app = models.ForeignKey(App, verbose_name='应用名称')
    paths = models.CharField(max_length=255, blank=True, null=True,  verbose_name='部署路径')
    users = models.CharField(max_length=255, blank=True, null=True,  verbose_name='系统用户')
    ports = models.IntegerField(blank=True, null=True, verbose_name='端口号')
    author = models.CharField(max_length=255, blank=True, null=True, verbose_name='部署人')
    dtime = models.DateField(blank=True, null=True, verbose_name='部署时间')
    documents = models.FileField(upload_to='./deploy', null=True, blank=True, verbose_name='部署文档')

    class Meta:
        ordering = ["name"]
        verbose_name = '部署信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.name

    def __str__(self):
        return u'%s' % self.name


class Business(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name='业务名称')
    description = models.CharField(max_length=255, null=True, blank=True, verbose_name='业务简介')
    contacts = models.CharField(max_length=255, blank=True, null=True, verbose_name='业务负责人')
    ol_date = models.DateField(blank=True, null=True, verbose_name='上线时间')
    deploys = models.ManyToManyField(Deploy, verbose_name='部署')
    details = models.TextField(null=True, blank=True, verbose_name='详情')
    annex = models.FileField(null=True, blank=True, verbose_name='附件')

    # 显示ManyToMany域
    def deploy_list(self):
        return ','.join([a.name for a in self.deploys.all()])

    deploy_list.short_description = '业务系统列表'

    class Meta:
        ordering = ["name"]
        verbose_name = '业务信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return u'%s' % self.name

    def __str__(self):
        return u'%s' % self.name

appinfo/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render_to_response
from .models import Server, Business, App, Deploy
from datetime import date, datetime


def server_list(request):
    server_lists = Server.objects.all()
    for server in server_lists:
        btime = server.buy_date
        yeard = server.service_range
        if btime is None:
            server.buy_date = 0
        else:
            y = int(btime.year)
            m = str(btime.month)
            d = str(btime.day)
            y = y + yeard
            s_expire = str(y) + '-' + m + '-' + d
            t_expire = datetime.strptime(s_expire, '%Y-%m-%d').date()

            today = date.today()
            distance = (today - t_expire).days
            if distance > 0:
                server.buy_date = 2
            else:
                server.buy_date = 1
            server.service_range = t_expire
        print(server.buy_date)

    return render_to_response('appinfo/server_list.html', locals())


def business_list(request):
    business_lists = Business.objects.all()
    return render_to_response('appinfo/business_list.html', locals())


def app_list(request):
    app_lists = App.objects.all()
    return render_to_response('appinfo/app_list.html', locals())


def deploy_list(request):
    deploy_lists = Deploy.objects.all()
    return render_to_response('appinfo/deploy_list.html', locals())

templates/appinfo/app_list.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block nav-head %}
	{{ block.super }}
{% endblock %}
{% block nav-top %}
       {{ block.super }}
{% endblock %}
{% block nav-side %}
	{{ block.super }}
{% endblock %}
{% block content %}
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            应用列表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th width="10%">应用名称</th>
											<th width="5%">语言</th>
											<th width="20%">功能说明</th>
											<th width="10%">研发团队</th>
											<th width="10%">研发日期</th>
                                            <th width="10%">联系人</th>
                                            <th width="35%">备注</th>
                                        </tr>
                                    </thead>
                                    <tbody>
									
{% for app in app_lists %}
                                        <tr class="odd gradeX">
                                            <td><a href="/addRecord?action=edit&issue_name={{ app.name }}" name="name">{{app.name}}</a></td>
                                            <td>{{app.language}}</td>
											<td class="center">{{app.function}}</td>
											<td class="center">{{app.teams}}</td>
											<td class="center">{{app.dev_time}}</td>
                                            <td class="center">{{app.contact}}</td>
                                            <td class="center">{{app.comment}}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        <!-- /.panel-body -->
                </div>
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}

templates/appinfo/business_list.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block nav-head %}
	{{ block.super }}
{% endblock %}
{% block nav-top %}
       {{ block.super }}
{% endblock %}
{% block nav-side %}
	{{ block.super }}
{% endblock %}
{% block content %}
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            业务系统列表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th width="10%">业务名称</th>
											<th width="20%">业务简介</th>
											<th width="10%">负责人</th>
											<th width="10%">上线时间</th>
											<th width="20%">部署应用</th>
											<th width="10%">附件</th>
											<th width="20%">详情</th>
                                        </tr>
                                    </thead>
                                    <tbody>
									
{% for business in business_lists %}
                                        <tr>
                                            <td>{{business.name}}</td>
                                            <td>{{business.description}}</td>
                                            <td>{{business.contacts}}</td>
                                            <td>{{ business.ol_date }}</td>
                                            <td>{{business.deploy_list}}</td>
											<td>{{business.annex}}</td>
											<td>{{ business.details }}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}

templates/appinfo/deploy_list.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block nav-head %}
	{{ block.super }}
{% endblock %}
{% block nav-top %}
       {{ block.super }}
{% endblock %}
{% block nav-side %}
	{{ block.super }}
{% endblock %}
{% block content %}
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            部署列表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th width="10%">部署名称</th>
                                            <th width="5%">服务器</th>
											<th width="5%">应用名称</th>
											<th width="15%">部署路径</th>
											<th width="10%">用户</th>
											<th width="10%">端口号</th>
											<th width="5%">部署人</th>
											<th width="5%">部署时间</th>
                                            <th width="5%">部署文档</th>
                                        </tr>
                                    </thead>
                                    <tbody>
									
{% for deploy in deploy_lists %}
                                        <tr class="odd gradeX">
                                            <td>{{deploy.name}}</td>
                                            <td>{{deploy.server.name}}</td>
                                            <td>{{deploy.app.name}}</td>
                                            <td>{{deploy.paths}}</td>
                                            <td>{{ deploy.users }}</td>
											<td>{{deploy.ports}}</td>
											<td>{{deploy.author}}</td>
											<td>{{deploy.dtime}}</td>
                                            <td>{{deploy.documents}}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        <!-- /.panel-body -->
                </div>
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}

templates/appinfo/server_list.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block nav-head %}
	{{ block.super }}
{% endblock %}
{% block nav-top %}
       {{ block.super }}
{% endblock %}
{% block nav-side %}
	{{ block.super }}
{% endblock %}
{% block content %}
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <br />
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            服务器列表
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th width="10%">名称</th>
											<th width="10%">IP</th>
											<th width="10%">服务代码</th>
											<th width="10%">品牌型号</th>
											<th width="10%">机房</th>
											<th width="10%">在保</th>
                                            <th width="10%">备注</th>
                                        </tr>
                                    </thead>
                                    <tbody>
									
{% for server in server_lists %}
                                        <tr class="odd gradeX">
                                            <td>{{server.name}}</td>
                                            <td>{{server.ip}}</td>
											<td><a href="{{ server.sn }}" title="序列号：{{ server.sn }}">{{server.sid}}</a> </td>
                                            <td><a href="#" target="_ablank" title="{{ server.mod }}
{{ server.feature }}">{{server.get_manufacturer_display}}</a></td>
                                            <td><a href="#" title="{{server.cabinet}}">{{server.get_idc_display }}</a> </td>
                                            <td>
                                                {% if server.buy_date == 1 %}
                                                    <span style="color: #3f903f;" ><a href="#" title="过保时间：{{ server.service_range }}">在保</a> </span>
                                                {% elif server.buy_date == 2 %}
                                                    <span style="color: #FF0000;"> <a href="#" title="过保时间：{{ server.service_range }}">过保</a></span>
                                                {% elif server.buy_date == 0 %}
                                                    <span style="color:blue;"><a href="#" title="过保时间：{{ server.service_range }}">未知</a></span>
                                                {% endif %}
                                            </td>
                                            <td>{{ server.comment }}</td>
                                        </tr>
{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        <!-- /.panel-body -->
                        </div>
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
{% endblock %}
{% block theme %}
	<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
	 <!-- DataTables JavaScript -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{% endblock %}